[package]
name = "one_brc_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-case-mapping = "0.5.0"
tokio = { version = "1.37.0", features = ["full" ]}